['generation']
n_batches = 500

model_name = "gpt2-small"
sae_release_short = "res-jb-feature-splitting"
# sae_ids = ["blocks.8.hook_resid_pre_768", "blocks.8.hook_resid_pre_1536", "blocks.8.hook_resid_pre_3072", "blocks.8.hook_resid_pre_6144", "blocks.8.hook_resid_pre_12288", "blocks.8.hook_resid_pre_24576"]
# "blocks.8.hook_resid_pre_49152", "blocks.8.hook_resid_pre_98304"
sae_ids = ["blocks.8.hook_resid_pre_24576"]
# activation_thresholds = [0.0, 0.1, 0.5, 1.5]
activation_thresholds = [1.5]
# activation_thresholds = [10.0, 20.0, 40.0, 60.0]
# activation_thresholds = [2.0, 4.0, 6.0, 8.0, 10.0]
n_batches_in_buffer = 16
remove_special_tokens = false


['analysis']
random_seed = 1234
min_subgraph_size = 150
max_subgraph_size = 200
min_subgraph_size_to_plot = 4
skip_subgraph_plots = false
skip_subgraph_pickles = false
include_metrics = true

['pca']
candidate_sizes = [5, 7, 12]
candidates_per_size = 3
n_batches_reconstruction = 50
recalculate_results = false