[model]
name = "gemma-2-2b"
sae_release_short = "gemma-scope-2b-pt-res-canonical"
sae_ids = [
    "layer_0/width_16k/canonical", 
    "layer_12/width_16k/canonical",
    "layer_18/width_16k/canonical",
    "layer_21/width_16k/canonical"
]

[processing]
remove_special_tokens = true
n_batches_reconstruction = 10
activation_threshold = 1.5
subgraph_sizes_to_plot = [5,6,7]
save_all_feature_acts = false